import os
import sys
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# Add parent directory to path to allow importing the Cascade model
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Attempt to import the SurfaceCascade model from the Cascade directory.
# Adjust the import path if the actual folder structure is slightly different.
try:
    from Cascade.cascade.model.surface_cascade import SurfaceCascade
except ImportError as e:
    print(f"Warning: Could not import SurfaceCascade. Please check the path. ({e})")
    SurfaceCascade = None

class SyndromeDataset(Dataset):
    """
    PyTorch Dataset for loading the syndrome data generated by stim.
    """
    def __init__(self, npz_path: str):
        if not os.path.exists(npz_path):
            raise FileNotFoundError(f"Dataset file not found: {npz_path}")
        
        data = np.load(npz_path)
        # Assuming X is shape (N, num_detectors) and Y is (N, num_observables)
        # We need to reshape X into the 3D grid format expected by the Convolutional Cascade model.
        # Note: The exact reshape dimensions depend on how the detectors map to the spacetime grid.
        # For a standard surface code, you might need to reshape this to (Batch, Channels, T, H, W).
        # Here we just load the raw vectors. You will need to add a reshape step here based on
        # your specific Cascade model input requirements.
        self.X = torch.from_numpy(data['X'])
        self.Y = torch.from_numpy(data['Y'])

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.Y[idx]

def train_model(distance: int, p_rate: float, epochs: int = 50, batch_size: int = 1024, lr: float = 1e-3):
    """
    Main training loop for the Cascade Neural Decoder.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # 1. Load Dataset
    dataset_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "datasets")
    npz_path = os.path.join(dataset_dir, f"dataset_d{distance}_p{p_rate}.npz")
    
    try:
        dataset = SyndromeDataset(npz_path)
    except FileNotFoundError as e:
        print(e)
        return
        
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    print(f"Loaded dataset for distance {distance}. Total samples: {len(dataset)}")

    # 2. Initialize Model
    if SurfaceCascade is None:
        print("Cannot initialize model without SurfaceCascade import. Exiting.")
        return
        
    # Initialize your model here. The parameters (like dim) might need to be adjusted
    # based on the exact signature of your SurfaceCascade class.
    model = SurfaceCascade(distance=distance).to(device)

    # 3. Define Loss and Optimizer
    # Since we are predicting 0 or 1 for logical errors, Binary Cross Entropy is appropriate.
    # BCEWithLogitsLoss is more numerically stable than sigmoid + BCELoss.
    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    # 4. Training Loop
    print("Starting training...")
    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        
        for batch_idx, (inputs, targets) in enumerate(dataloader):
            inputs, targets = inputs.to(device), targets.to(device)
            
            # --- IMPORTANT NOTE ---
            # Stim outputs a 1D flat array for detectors per shot.
            # 3D Convolutional models (like Cascade) expect inputs in a spatial grid (Batch, Channels, T, H, W).
            # You must reshape 'inputs' here to match your model's expected shape before passing it in.
            # inputs = inputs.view(inputs.size(0), 1, distance, distance, distance) # Example reshaping
            
            optimizer.zero_grad()
            
            # Forward pass
            outputs = model(inputs)
            
            # Calculate loss
            loss = criterion(outputs, targets)
            
            # Backward pass and optimize
            loss.backward()
            optimizer.step()
            
            running_loss += loss.item()
            
        epoch_loss = running_loss / len(dataloader)
        print(f"Epoch [{epoch+1}/{epochs}] - Loss: {epoch_loss:.6f}")

    # 5. Save the trained model
    checkpoint_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "checkpoints")
    os.makedirs(checkpoint_dir, exist_ok=True)
    
    save_path = os.path.join(checkpoint_dir, f"cascade_d{distance}.pth")
    torch.save(model.state_dict(), save_path)
    print(f"Training complete! Model saved to {save_path}")

if __name__ == "__main__":
    # Example: Train the model for Distance 5 using the dataset generated at p=0.01
    TARGET_DISTANCE = 5
    TARGET_P = 0.01
    
    # Increased epochs and batch_size for powerful GPU (e.g., RTX 6000)
    train_model(distance=TARGET_DISTANCE, p_rate=TARGET_P, epochs=50, batch_size=1024)
